export { GroupRoute } from "./group"
export { DirectionRoute } from "./direction"
export { FacultyRoute } from "./faculty"
export { UserRoute } from "./user"
export { AuthRoute } from "./auth"
export { LessonRoute } from "./lesson"
export { SubjectRoute } from "./subject"
export { StudentAttendanceRoute } from "./studentAttendance"
