
export const SECRET_KEY = process.env.SECRET_KEY!
export const REFRESH_SECRET_KEY = process.env.REFRESH_SECRET_KEY!
export const TOKEN_EXPIRATION_TIME = process.env.TOKEN_EXPIRATION_TIME!
export const REFRESH_TOKEN_EXPIRATION_TIME = process.env.REFRESH_TOKEN_EXPIRATION_TIME! 
